### ISSUE TITLE
 `oracle::ResultSet<'_, oracle::Row>` is not an iterator

### ISSUE THREAD

**Issue by sincerefly** [kubo/rust-oracle#12]
Run the demo(select.rs) , the error when build:

```
error[E0277]: `oracle::ResultSet<'_, oracle::Row>` is not an iterator
  --> src/main.rs:13:23
   |
13 |     for row_result in rows {
   |                       ^^^^ `oracle::ResultSet<'_, oracle::Row>` is not an iterator
   |
   = help: the trait `std::iter::Iterator` is not implemented for `oracle::ResultSet<'_, oracle::Row>`
   = note: required by `std::iter::IntoIterator::into_iter`

error: aborting due to previous error
```

ENV:
rustc 1.36.0-nightly (938d4ffe1 2019-04-27)

**Comment by kubo** [comment]
Could you use `for row_result in &rows` instead of `for row_result in rows`?
I guess that you uses oracle 0.2.x. However the select.rs you see is for unreleased 0.3.x. See [incompatible changes in 0.3.0](https://github.com/kubo/rust-oracle/blob/master/ChangeLog.md#030-xxx).

I must release 0.3.0, but I won't do in the near future. I have some issues in other projects whose priority is higher than this.

**Comment by sincerefly** [comment]
thanks, use `&rows` works well
