### ISSUE TITLE
static linking possible?

### ISSUE THREAD

**Issue by arve0** [kubo/rust-oracle#23]
Hi! Thanks for the library. Is it possible to statically link the oracle instant client?

According to this [stackoverflow post about the same in go](https://stackoverflow.com/questions/38785691/trying-to-build-static-cgo-executable-with-oracle-libraries-on-linux-ubuntu) it seems possible, but I'm new to linking binaries.

**What I have tried so far?**
- Make sure it builds and runs locally.
- Build with [emk/rust-musl-builder](/emk/rust-musl-builder). Running the static build on another machine fails with an ORA runtime error. Did not write down the error code, and on another machine now, but the error was about missing oracle client library.
- Looking for $ORACLE_HOME/bin/relink and libclntst.a after installing oracle-instantclient19.5-devel on oraclelinux 7. It installs these libraries: libclntsh.so, libclntsh.so.12.1, libclntshcore.so, libmql1.so, libclntsh.so.10.1, libclntsh.so.18.1, libclntshcore.so.19.1, libnnz19.so, libclntsh.so.11.1, libclntsh.so.19.1, libipc1.so, libocci.so.19.1

**Comment by tatref** [comment]
Hi,

Doc says it's not supported: https://docs.oracle.com/en/database/oracle/oracle-database/18/rnrdm/linux-platform-issues.html#GUID-D76F3CA5-B23B-4C08-88B2-F9D3DE3A19E3

Older versions (11.2) said you'd need to generate the `.a`: https://docs.oracle.com/cd/E11882_01/install.112/e24339/post_inst_task.htm#HPCLI1340

**Comment by kubo** [comment]
@arve0 
> Is it possible to statically link the oracle instant client?

No. Rust-oracle uses [ODPI-C](https://oracle.github.io/odpi/), which loads Oracle client libraries at runtime by using dlopen on Unix or LoadLibrary on Windows. In addition Oracle client static libraries are not supported as follows.

@tatref Thanks for the usable links. I checked more.

Oracle Database Client Installation Guide for Linux ([Oracle 12.1](https://docs.oracle.com/database/121/LACLI/post_inst_task.htm#LACLI1401), [Oracle 11.2](https://docs.oracle.com/cd/E11882_01/install.112/e24322/post_inst_task.htm#LACLI1340)) has "Generating the Client Static Library" section. However Release Notes for Linux says it isn't supported.

[Oracle 12.1 Release Notes for Linux](https://docs.oracle.com/database/121/LADBN/toc.htm#CJAEEGBG)
> You must use the dynamic Oracle client libraries to link the client code on Linux. Do not link the static Oracle client libraries.

[Oracle 11.2 Release Notes for Linux](https://docs.oracle.com/cd/E11882_01/relnotes.112/e23558/toc.htm#sthref9)
> The use of the client static library is not supported.

The "Generating the Client Static Library" section are not found since Oracle 12.2.
