### ISSUE TITLE
get raw blob data?

### ISSUE THREAD

**Issue by swuecho** [kubo/rust-oracle#5]
I have multiple f32 stored  together as blob.  it there a way to read the raw blob. or even better to read the f32 to a vec. 

I figure out sqlValue.get\<f32\>() should get a single one, but I have multiple of them. Thanks.

**Comment by kubo** [comment]
I was going to suggest that "Get the blob data as `Vec<u8>` and convert them to `Vec<f32>`.
However it couldn't. Fetching `RAW` data type columns as `Vec<u8>` is available but fetching `BLOB` data type columns as `Vec<u8>` is missing. I'll fix it at the next release.

Instead of it, get the blob data as `String` and convert them to `Vec<f32>`. When binary data are fetched as string, they are converted to hexadecimal strings as sqlplus does. So you can get f32 data in blob as hexadecimal string.

1. Add hex crate to Cargo.toml
   ```
   [dependencies]
   hex = "0.3"
   ```
2. Create a conversion function from hexadecimal string to `Vec<f32>`.
   ```rust
   extern crate hex;
   use std::mem;
   use std::slice;

   fn hexstr_to_f32vec(s: &str) -> Vec<f32> {
       let raw = hex::decode(s).unwrap();
       let len = raw.len() / mem::size_of::<f32>();
       unsafe { slice::from_raw_parts(raw.as_ptr() as *const f32, len) }.to_vec()
   }
   ```
3. Fetch blob data as `String` and convert it to `Vec<f32>`
   ```rust
   let conn = oracle::Connection::connect(username, password, database, &[]).unwrap();
   let hexstr = conn.query_row_as::<String>("select blob_column from table_name where ...", &[]).unwrap());
   let f32vec = hexstr_to_f32vec(&hexstr);
   ```
4. Otherwise, fetch blob data as a custom type implementing [`FromSql`][] trait.
   ```rust
   #[derive(Debug)]
   struct CustomType(Vec<f32>);

   impl oracle::FromSql for CustomType {
       fn from_sql(val: &oracle::SqlValue) -> oracle::Result<CustomType> {
           let hexstr = val.get::<String>()?;
           Ok(CustomType(hexstr_to_f32vec(&hexstr)))
       }
   }

   ...

   let conn = oracle::Connection::connect(username, password, database, &[]).unwrap();
   let custom_type = conn.query_row_as::<CustomType>("select blob_column from table_name where ...", &[]).unwrap());
   let f32vec = custom_type.0;
   ```

[`FromSql`]: https://docs.rs/oracle/*/oracle/trait.FromSql.html

**Comment by swuecho** [comment]
Thanks for the detailed answer. 

the approach works great. the only problem is the endianess. 
```
fn hexstr_to_f32vec(s: &str) -> Vec<f32> {
    let raw = hex::decode(s).unwrap();
    let len = raw.len() / mem::size_of::<f32>();
    unsafe { slice::from_raw_parts(raw.as_ptr() as *const f32, len) }.to_vec()
}
```
the raw is in bigendian. so I have to add `raw.reverse` to get the right value.

also, get the blob value as `Vec<u8> ` is great, will save the round trip conversion.

**Comment by kubo** [comment]
@swuecho 
oracle 0.1.1 was published. It can get blob as `Vec<u8>`.

I checked that bigendian f32 values in blob could be fetch as `Vec<f32>` by the following code.
```rust
use std::mem;
use std::slice;

fn raw_to_f32vec(raw: &[u8]) -> Vec<f32> {
    let len = raw.len() / mem::size_of::<f32>();
    let mut f32vec = Vec::with_capacity(len);
    for u32val in unsafe { slice::from_raw_parts(raw.as_ptr() as *const u32, len) } {
        f32vec.push(f32::from_bits(u32::from_be(*u32val)))
    }
    f32vec
}

...

let conn = oracle::Connection::connect(username, password, database, &[]).unwrap();
let raw = conn.query_row_as::<Vec<u8>>("select blob_column from table_name where ...", &[]).unwrap());
let f32vec = raw_to_f32vec(&raw);
```

**Comment by swuecho** [comment]
Thanks @kubo. this works perfectly.
